<?php

namespace Database\Seeders;

use App\Models\MetaDeProducto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MetasSeeder_1_16 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 1,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP1',
            'nombre' => '1,  Impulsar un programa de potabilización de agua en los  municipios con más altos niveles de pobreza a partir de la adaptación de tecnologías.',
            'indicador_meta' => 'No. de programas de potabilización impulsados',
            'peso' => 0,
            'linea_base' => null,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => null,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => null,
            'recurso_year_3' => null,
            'recurso_year_4' => null,
            'recurso_cuatrienio' => null,
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 2,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP2',
            'nombre' => '2,  Impulsar un acuerdo público-comunitario para la autoconstrucción y construcción progresiva como alternativa de vivienda digna en la Región RAP Eje Cafetero.',
            'indicador_meta' => 'No. De acuerdos publico comunitarios impulsados para la autoconstrucción como alternativa de vivienda digna en la RAP Eje Cafetero.',
            'peso' => null,
            'linea_base' => null,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 30.000.000',
            'recurso_year_3' => '$ 30.000.000',
            'recurso_year_4' => '$ 30.000.000',
            'recurso_cuatrienio' => '$ 90.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 3,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP3',
            'nombre' => '3,  Articular e impulsar los proyectos contenidos en el Plan de  Educación Regional 2019 -2031',
            'indicador_meta' => 'No. De proyectos contenidos en el Plan de Educación 2019 - 2033  Articulados e Impulsados',
            'peso' => null,
            'linea_base' => 10,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 2,
            'meta_year_4' => 3,
            'meta_cuatrienio' => 3,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 10.000.000',
            'recurso_year_3' => '$ 10.000.000',
            'recurso_year_4' => '$ 10.000.000',
            'recurso_cuatrienio' => '$ 30.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 3,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP4',
            'nombre' => '4,  Promover la operación del clúster de educación superior en la  región RAP Eje Cafetero',
            'indicador_meta' => 'No. De operaciones del cluster de educación superiór promovidas',
            'peso' => null,
            'linea_base' => 1,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 10.000.000',
            'recurso_year_3' => '$ 10.000.000',
            'recurso_year_4' => '$ 10.000.000',
            'recurso_cuatrienio' => '$ 30.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 4,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP4',
            'nombre' => '5,  Promover  Acuerdos regionales contra las violencia, el trabajo infantil, el consumo de estupefacientes, el suicidio y la inequidad de género, e implementar un plan de seguimiento a los  indicadores regionales en estos temas.',
            'indicador_meta' => 'No. De acuerdos regionales promovidos y planes de seguimiento implementados',
            'peso' => null,
            'linea_base' => null,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 2,
            'meta_cuatrienio' => 2,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 30.000.000',
            'recurso_year_3' => '$ 30.000.000',
            'recurso_year_4' => '$ 3.000.000',
            'recurso_cuatrienio' => '$ 63.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 1,
            'politica_id' => 1,
            'programa_id' => 5,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR1P1MP6',
            'nombre' => '6,  Crear e implementar un Observatorio Regional de Seguimiento y Promoción de los ODS.',
            'indicador_meta' => 'No. De observatorios regionales de seguimientos a los ODS creados e implementados',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 100.000.000',
            'recurso_year_3' => '$ 100.000.000',
            'recurso_year_4' => '$ 100.000.000',
            'recurso_cuatrienio' => '$ 300.000.000',
        ]);

// -----------------------------

        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 6,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR2P2MP1',
            'nombre' => '1. PRODUCTO: Crear el Sistema Regional de Innovación, con su respectivo  plan estratégico.',
            'indicador_meta' => 'No. de sistemas regionales de Innovación creados con su respectivo Plan Estrategico',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => 1,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 48.000.000',
            'recurso_year_3' => '$ 30.000.000',
            'recurso_year_4' => '$ 30.000.000',
            'recurso_cuatrienio' => '$ 108.000.000',
        ]);

        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 6,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'null',
            'nombre' => 'PRODUCTO: Acordar y poner en operación un Plan de Transición Energética Regional a 2033, como una contribución a la lucha contra el  cambio climático, para ser adoptados por las entidades territoriales  asociadas a la RAP EC',
            'indicador_meta' => null,
            'peso' => null,
            'linea_base' => null,
            'year' => null,
            'meta_year_1' => null,
            'meta_year_2' => null,
            'meta_year_3' => null,
            'meta_year_4' => null,
            'meta_cuatrienio' => null,
            'recurso_year_1' => null,
            'recurso_year_2' => null,
            'recurso_year_3' => null,
            'recurso_year_4' => null,
            'recurso_cuatrienio' => null,
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 6,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR2P2MP2',
            'nombre' => '2. PRODUCTO: Impulsar la creación del Centro de Investigaciones Regionales de Biotecnología y Bioeconomía y apoyar su operación',
            'indicador_meta' => 'No. De centros de Investigaciones Regionales de Biotecnología y Bioeconomía impulsados y apoyados.',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 52.000.000',
            'recurso_year_3' => '$ 70.000.000',
            'recurso_year_4' => '$ 70.000.000',
            'recurso_cuatrienio' => '$ 192.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 7,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'null',
            'nombre' => 'PRODUCTO: Articular la institucionalidad pública para el diseño de un Plan Regional de Conectividad Digital',
            'indicador_meta' => null,
            'peso' => null,
            'linea_base' => null,
            'year' => null,
            'meta_year_1' => null,
            'meta_year_2' => null,
            'meta_year_3' => null,
            'meta_year_4' => null,
            'meta_cuatrienio' => null,
            'recurso_year_1' => null,
            'recurso_year_2' => null,
            'recurso_year_3' => null,
            'recurso_year_4' => null,
            'recurso_cuatrienio' => null,
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 8,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR2P2MP3',
            'nombre' => '3. PRODUCTO: Impulsar la marca Hecho en la Región Eje Cafetero.',
            'indicador_meta' => 'No. De marcas impulsadas',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 540.000.000',
            'recurso_year_3' => '$ 150.000.000',
            'recurso_year_4' => '$ 160.000.000',
            'recurso_cuatrienio' => '$ 850.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 8,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR2P2MP4',
            'nombre' => '4. PRODUCTO: Impulsar la creación y consolidación de las Cadenas Regionales de Valor.',
            'indicador_meta' => 'No. De Cadenas Regionales de valor impulsadas',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => null,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 280.000.000',
            'recurso_year_3' => '$ 200.000.000',
            'recurso_year_4' => '$ 220.000.000',
            'recurso_cuatrienio' => '$ 700.000.000',
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 2,
            'programa_id' => 9,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'null',
            'nombre' => 'PRODUCTO: Promover un programa regional de reconversión   tecnológica para la disposición final de residuos sólidos',
            'indicador_meta' => null,
            'peso' => null,
            'linea_base' => null,
            'year' => null,
            'meta_year_1' => null,
            'meta_year_2' => null,
            'meta_year_3' => null,
            'meta_year_4' => null,
            'meta_cuatrienio' => null,
            'recurso_year_1' => null,
            'recurso_year_2' => null,
            'recurso_year_3' => null,
            'recurso_year_4' => null,
            'recurso_cuatrienio' => null,
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 3,
            'programa_id' => 10,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'null',
            'nombre' => 'PRODUCTO: Impulsar la creación y operación del Distrito Regional Agroindustrial a través de nodos especializados. ',
            'indicador_meta' => null,
            'peso' => null,
            'linea_base' => null,
            'year' => null,
            'meta_year_1' => null,
            'meta_year_2' => null,
            'meta_year_3' => null,
            'meta_year_4' => null,
            'meta_cuatrienio' => null,
            'recurso_year_1' => null,
            'recurso_year_2' => null,
            'recurso_year_3' => null,
            'recurso_year_4' => null,
            'recurso_cuatrienio' => null,
        ]);
        MetaDeProducto::create([
            'periodo_id' => 1,
            'hecho_id' => 2,
            'politica_id' => 3,
            'programa_id' => 11,
            'indicador_id' => 1,
            'user_id' => 1,
            'codigo' => 'HR2P3MP1',
            'nombre' => '1. PRODUCTO: Constituir el Sistema Regional de Abastecimiento  Alimentario, con un sistema de seguimiento a través de un  Observatorio Regional.',
            'indicador_meta' => 'No. de sistemas regionales de abastecimiento alimentario, con un sistema de seguimiento a través de un observatorio regional construidos',
            'peso' => null,
            'linea_base' => 0,
            'year' => 2021,
            'meta_year_1' => 1,
            'meta_year_2' => 1,
            'meta_year_3' => 1,
            'meta_year_4' => 1,
            'meta_cuatrienio' => 1,
            'recurso_year_1' => null,
            'recurso_year_2' => '$ 374.000.000',
            'recurso_year_3' => '$ 100.000.000',
            'recurso_year_4' => '$ 100.000.000',
            'recurso_cuatrienio' => '$ 574.000.000',
        ]);


    }
}
